repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=99]
        exclude: |
          (?x)^(
              \.git|
              __pycache__|
              build|
              dist|
              \.venv|
              \.pytest_cache|
              outputs|
              resources|
              test\.ipynb
          )/
        types: [python]
        additional_dependencies: [black]
