name: mint
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip=24.0
  - cudatoolkit=11.8
  - biopython=1.81
  - einops=0.7.0
  - fairscale=0.4.13
  - hhsuite=3.3.0
  - hmmer=3.3.2
  - hydra-core=1.3.2
  - ipykernel=6.25.0
  - ipython=8.15.0
  - jupyter_client=8.3.0
  - jupyter_core=5.3.0
  - kalign2=2.04
  - omegaconf=2.3.0
  - openmm=8.0.0
  - pandas=2.0.3
  - pdbfixer=1.9
  - pytest=7.4.4
  - pytorch=2.0.1
  - pytorch-mutex=1.0
  - pip:
      - torch==2.0.1
      - torchvision==0.15.2
      - torchaudio==2.0.2
      - absl-py==2.1.0
      - datasets==2.14.0
      - deepspeed==0.10.0
      - filelock==3.12.2
      - gdown==4.7.3
      - huggingface-hub==0.16.4
      - jupyterlab-widgets==3.0.10
      - lightning==2.0.7
      - matplotlib==3.7.2
      - numpy==1.24.3
      - openpyxl==3.1.3
      - protobuf==4.24.0
      - rdkit-pypi==2023.3.2
      - regex==2024.4.16
      - requests==2.31.0
      - scikit-learn==1.3.0
      - scipy==1.11.1
      - sentencepiece==0.2.0